### ISSUE TITLE
Can't add as dependency on both stable and nightly cargo

### ISSUE THREAD

**Issue by programble** [whitequark/rust-xdg#13]
Specifying `2.0.0` works on stable, resolving to `2.0.0-pre7`, but not on nightly, which says it doesn't match any versions.

Specifying `2.0.0-pre7` works on nightly, but stable fails to even parse the `Cargo.toml`.

Doesn't look like there's been any changes since `2.0.0-pre7`. Could `2.0.0` just be released?

**Comment by whitequark** [comment]
> Specifying 2.0.0 works on stable

Yep. This was a bug in Cargo. See https://github.com/rust-lang/cargo/issues/2222.

I'll release 2.0.0.

**Comment by whitequark** [comment]
Released
