### ISSUE TITLE
Issue with XDG_RUNTIME_DIR check

### ISSUE THREAD

**Issue by meh** [whitequark/rust-xdg#15]
The environment variable is defined on my system but the directory doesn't actually exist, which makes `BaseDirectories::new` return an error.

Is this actually how it should be handled? I haven't had issues with programs that follow the XDG convention.

**Comment by whitequark** [comment]
Hm, a careful reading of the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) gives:

> If, when attempting to write a file, the destination directory is non-existant an attempt should be made to create it with permission 0700. 

So we should probably lazily return an error.

**Comment by meh** [comment]
Could you also publish the new version on crates.io please?

**Comment by whitequark** [comment]
Done
