### ISSUE TITLE
`path_exists` should follow symlinks

### ISSUE THREAD

**Issue by damselem** [whitequark/rust-xdg#21]
Today I encountered this issue when trying to use [alacritty](https://github.com/jwilm/alacritty). It seems it relies on this crate in order to check whether a certain configuration file (`alacritty.yml`) exists ([link](https://github.com/jwilm/alacritty/blob/e34dccdabf210612666cbb9d22d7afff23487eaf/src/config.rs#L1219)). I do have that file in one of the valid locations, but it's symlinked from a parent directory.
Removing the symlink and replacing it with a regular file seems to fix the problem.

$XDG_CONFIG_HOME/alacritty -> /Users/damselem/.dotfiles/config/alacritty

However, I'd expect the [`path_exists`](https://github.com/whitequark/rust-xdg/blob/090afef2509d746e48d6bfa9b2e1ef6dc4564448/src/lib.rs#L546) method to follow symlinks.

**Comment by whitequark** [comment]
Thanks for the report. Is there any chance you could prepare a pull request?

**Comment by damselem** [comment]
Unfortunately I don't have any experience with Rust.

**Comment by davvid** [comment]
I wrote  a unit test that suggests that symlinks are already correctly handled.  Please let me know if the unit test is insufficient -- I intended for it to match this setup / use-case..
