### ISSUE TITLE
Use `std::env::home_dir` instead of `std::env::var_os("HOME")`

### ISSUE THREAD

**Issue by tbu-** [whitequark/rust-xdg#3]
[`std::env::home_dir`](https://doc.rust-lang.org/std/env/fn.home_dir.html) has a sensible fallback in case `$HOME` is not set.

**Comment by whitequark** [comment]
`USERPROFILE` is Windows-only. What is the purpose of this change?

**Comment by tbu-** [comment]
The fallback exists, it just isn't documented. See https://github.com/rust-lang/rust/pull/29690.

**Comment by whitequark** [comment]
OK. But what is the value of the change? If `HOME` is not set, the environment is not even nearly XDG compliant, I believe...

**Comment by tbu-** [comment]
The value is that the library doesn't panic in this case, making it more useful for programs trying to be robust.

I wanted to use this library to make cargo XDG-compliant, but they probably won't like it if it generated an error in more cases due to such a change.

**Comment by whitequark** [comment]
Hm, it's true that something like cargo shouldn't really care if the environment is perfectly XDG compliant or not.

**Comment by tbu-** [comment]
Thanks!
