### ISSUE TITLE
`list_data_files` should follow symlinks

### ISSUE THREAD

**Issue by piegamesde** [whitequark/rust-xdg#36]
`xdg.list_local_files` will simply list all symlinks contained in that directory, instead of providing their targets' content. Symlink-joining folders in a data directory is a rather common pattern, especially when using Nix (although I just ran into this in a different context).

**Comment by whitequark** [comment]
Would you be willing to prepare a PR?

**Comment by piegamesde** [comment]
I had a look at the code and noticed that it didn't recurse into sub-directories. Thus, it kind of makes sense if the code lists some entries as symlinks if there are any. We could resolve them of course, but what for? The remaining cases (the traversal to the directory itself) are already resolved by `std::fs::read_dir`, see #21.

As far as I can tell, recursive walks are a bit out of scope for this crate, especially as `walkdir` best provides that functionality. I'll see if I can come up with some additions that help with my use cases. Sadly, changing the return type of many methods from `Vec` to `impl Iterator` would be a breaking change.

**Comment by whitequark** [comment]
It seems like the issue has been resolved to the extent of the scope.
