### ISSUE TITLE
Is `list_config_files_once` stable?

### ISSUE THREAD

**Issue by hxzhao527** [whitequark/rust-xdg#37]
Now the method `list_config_files_once` impl:
https://github.com/whitequark/rust-xdg/blob/c2921e01ad47759fdffcbd77cb7e595936b923ad/src/lib.rs#L728-L745

travel `$HOME` first.

But is it stable? 

e.g. [Autostart Directories](https://specifications.freedesktop.org/autostart-spec/0.5/ar01s02.html) depends on the travel order.

**Comment by whitequark** [comment]
If I remember correctly, this function implements the following part of the XDG Base Directories spec:

> The order of base directories denotes their importance; the first directory listed is the most important. When the same information is defined in multiple places the information defined relative to the more important base directory takes precedent. The base directory defined by $XDG_DATA_HOME is considered more important than any of the base directories defined by $XDG_DATA_DIRS. The base directory defined by $XDG_CONFIG_HOME is considered more important than any of the base directories defined by $XDG_CONFIG_DIRS.

(from [Environment variables](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html)).

**Comment by hxzhao527** [comment]
> If I remember correctly, this function implements the following part of the XDG Base Directories spec:
> 
> > The order of base directories denotes their importance; the first directory listed is the most important. When the same information is defined in multiple places the information defined relative to the more important base directory takes precedent. The base directory defined by $XDG_DATA_HOME is considered more important than any of the base directories defined by $XDG_DATA_DIRS. The base directory defined by $XDG_CONFIG_HOME is considered more important than any of the base directories defined by $XDG_CONFIG_DIRS.
> 
> (from [Environment variables](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html)).

thanks. no more question.
