### ISSUE TITLE
Doesn't compile on Rust 1.2.0, stable and beta

### ISSUE THREAD

**Issue by tbu-** [whitequark/rust-xdg#6]
It looks like running on these versions is a requirement for inclusion in cargo, see the failing tests in https://github.com/rust-lang/cargo/pull/2127 (https://travis-ci.org/rust-lang/cargo/builds/90074618).

**Comment by whitequark** [comment]
Would you write a PR? I don't have time to set up multirust right now.

**Comment by whitequark** [comment]
Oh, I've looked at the error--it's ridiculous... that `#![feature]` is only used in tests anyway. But I don't know how to conditionally enable it only on tests since it's a crate attribute.

**Comment by whitequark** [comment]
I think this is fixed in 2c6820ce.

**Comment by whitequark** [comment]
Published pre4.
