### ISSUE TITLE
Drop the `home` dependency?

### ISSUE THREAD

**Issue by nickelc** [whitequark/rust-xdg#62]
This crate supports the Base Directory spec only for `unix` & `redox` and not `windows`.
And the `home` crate basically boils down to calling `std::env::home_dir()` for the supported targets.

[`home` source](https://github.com/rust-lang/cargo/blob/1cd4ef32fb9c7b819c45f1b8e335d04f29cba7ce/crates/home/src/lib.rs#L71-L75)
```rust
#[cfg(any(unix, target_os = "redox"))]
fn home_dir_inner() -> Option<PathBuf> {
    #[allow(deprecated)]
    std::env::home_dir()
}
```

Would it not make sense to just drop it and switch back to `std::env::home_dir()` when the function is only deprecated because the [function's behavior may be unexpected on Windows](https://doc.rust-lang.org/stable/std/env/fn.home_dir.html)?

**Comment by whitequark** [comment]
I think it makes more sense to return `%USERPROFILE%` or the result of `GetUserProfileDirectory` and skip `%HOME%` on Windows.

**Comment by utkarshgupta137** [comment]
Yeah, if Windows support is not planned, then might as well remove the `home` dep.
