### ISSUE TITLE
HOME Override

### ISSUE THREAD

**Issue by Swivelgames** [whitequark/rust-xdg#68]
## The Problem

It would be great if we could default to `$HOME`, but also specify a custom HOME dir for use as the prefix.

There are a number of scenarios where this could be leveraged by implementers:

- Running command using a daemon user
- Managing different user's files
- `su` (SwitchUser) Functionality
- Integration Testing

The latter is what I'm looking for immediately, but the more the merrier.

## Solution

This could be achieved by providing a simple interface for setting the HOME override:

```rust
xdg::with_home("/home/my-custom-home");
xdg::with_home_prefix("/home/my-custom-home", "program-name");
xdg::with_home_profile("/home/my-custom-home", "program-name", "profile-name");
```

**Comment by whitequark** [comment]
> * Running command using a daemon user
> * `su` (SwitchUser) Functionality
> * Managing different user's files

These don't seem like desktop use cases to me.

> * Integration Testing

This is the only one that's clearly in scope. But, why not override `HOME` in your test?

**Comment by Swivelgames** [comment]
Those first three were more from the perspective of Rust-based CLI applications and/or Daemons. In fact, while I do need this for Integration Testing right now, I will also need it for those other scenarios shortly.

The idea for this being that it would default to the current method for determining `HOME`, but it could be overridden.

-----

I admit that the `specifying a username` portion is probably quite a bit out of scope for this package 😅 Plus, something like that could be implemented relatively effortlessly by someone using this package if they had the ability to specify a different `HOME`.

**Comment by whitequark** [comment]
So, what's wrong with `setenv("HOME", "whatever")`?

**Comment by Swivelgames** [comment]
I thought about that initially, but it just seems like a bit of an anti-pattern to use `setenv("HOME", "whatever")`. It relies on the understanding that `xdg` will honor it, even though it's not explicitly part of `xdg`'s public API. It's a bit like accessing / manipulating / relying-on internal APIs. On the surface it just doesn't seem like a stable or reliable approach, especially given that it affects more than just `xdg`'s behavior.

```rust
let other_home = "/home/away-from-home";
let home = std::env::home_dir();

setenv("HOME", other_home);
let xdg_dirs = xdg::with_profile("program-name");
setenv("HOME", home);
```

Versus:

```rust
xdg::with_home("/home/away-from-home", "program-name")
```

I decided to try my hand at implementing it. I'm curious what your thoughts are. I have no expectation that it will be merged, but I wanted to try out the ergonomics for myself.

I also added some improvements to the existing tests where I found gaps, including improving some false tests.

**Comment by whitequark** [comment]
> . It relies on the understanding that `xdg` will honor it, even though it's not explicitly part of `xdg`'s public API.

It is definitely a part of the public API and if that's unclear we should just document it.

**Comment by whitequark** [comment]
Reading over the [API docs](https://docs.rs/xdg/latest/xdg/struct.BaseDirectories.html#method.new): 

> The following environment variables are examined:
>
> - HOME; if not set: use the same fallback as std::env::home_dir(); if still not available: return an error.

How is this *not* explicitly a part of the public API?

**Comment by whitequark** [comment]
> I was hoping to use this for a multi-user daemon for DEs.

I think *this* might actually be in-scope.

**Comment by whitequark** [comment]
Let's reopen this--I'll think about the API in a bit.

**Comment by whitequark** [comment]
Huh, you can close issues like that?

**Comment by Swivelgames** [comment]
Uhhh... I didn't think I could o.O wtf?

**Comment by Swivelgames** [comment]
That's odd. I don't know why it closed one of your issues because I merged a PR in a different repo. That's kind of sketchy!
